### PR TITLE
CR-1200532 - Revert "Merge commit '27e19b6a149145d6c1e6fd44858f955104a633f8' into

### PR DESCRIPTION
**Pull request by dmicheletti**
…2024.1"

Mistakenly merged a series of commits that were not intended during PR352.

This reverts commit b11e17ecbcf581f2739a6d7056e7f61b74182996, reversing changes made to 20946e2f2d4520f055fbcf5d1d527b53ee2ca94c.

### CODE REVIEW

**Comment by dmicheletti** [comment]
This PR is intending to completely undo PR 352, which was not 100% in sync with upstream when the merge was committed.

**Comment by dmicheletti** [comment]
Also needed to revert the automatic catalog file commit; adding that to this PR.

**Comment by dmicheletti** [comment]
Added original CR to get past the build pipeline

**Comment by sabarinaxil** [comment]
test this please

**Comment by sabarinaxil** [comment]
retest this please

**Comment by sabarinaxil** [comment]
retest this please

**Pull request merged**
