### PR TITLE
CR-1135368 [2021.2] HSDP CED added 

### PR DESCRIPTION
**Pull request by rishibharadwajs**
[2021.2] HSDP CED added

### CODE REVIEW

**Comment by vsrunga** [comment]
@rishibharadwajs - As 2022.1 is a released branch, merge can happen only for the pull requests that are SRCB approved, else pipeline will fail. Please go though "CR Requirements for Released Branches" section for more details https://gitenterprise.xilinx.com/XHUB/XilinxCEDStore/blob/master/README.md

**Comment by rishibharadwajs** [comment]
[CR-1135368](https://jira.xilinx.com/browse/CR-1135368)
CR has been created and approved.

**Comment by Abhinav2016** [comment]
OK to test

**Comment by Abhinav2016** [comment]
ok to test

**Comment by lay-xilinx** [comment]
ok to test

**Comment by lay-xilinx** [comment]
retest this please

**Comment by lay-xilinx** [comment]
The last line of this code snippet is incorrect.  It is trying to use the part as a TCL command.  Please update this PR.  

_load part/pkg stuff here_
  set toks [split ${PROJECT_PARAM.PART} "-"]
  set part [lindex $toks 0]
  log "part : $part $currentDir"
 _run factory proc to create proper get_all_quads and other device-specific procs_
  $part

**Pull request merged**
