### PR TITLE
CR-1160152 HSDP CED for 2023.1

### PR DESCRIPTION
**Pull request by havishxilinx**

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
retest this please

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
retest this please

**Comment by lay-xilinx** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
retest this please

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
retest this please

**Comment by ADubeyAMD** [comment]
Hi @havishxilinx, the pipeline is flagging an error: 04:06:51 [18-Apr-2023 04:06:50] {update_catalog.py:699} INFO - invalid command name "xcv70"

Please correct line 67 of your hsdp_help.tcl file.
image

**Comment by ADubeyAMD** [comment]
@havishxilinx if you are trying to add a new CED to Github then please also push it to GitEnterprise. Since this design is being added after the EA date therefore it needs to be pushed to both the locations. Also please raise an SRCB request for both GitEnterprise and GitHub PR's. This can be done by on CR  and mentioning about both GITE and GITHub PR's. Thank you

**Comment by ADubeyAMD** [comment]
@havishxilinx please check the comments and fix the files

**Pull request closed without merging**
