### PR TITLE
CR-1174449 - Change remaps property so it is properly displayed in NOC GUI

### PR DESCRIPTION
**Pull request by brogan-miner**

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by brogan-miner** [comment]
Please retest

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
@brogan-miner , since we are in super SRCB now so please attach the approval for the pipeline to run successfully; 
image

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
retest this please

**Comment by lay-xilinx** [comment]
retest this please

**Comment by lay-xilinx** [comment]
ok to test

**Pull request merged**
