### PR TITLE
CR-1196619 : Removing "ACAP" from displayed image

### PR DESCRIPTION
**Pull request by dmicheletti**
Also replacing "Xilinx" with "AMD" in text

### CODE REVIEW

**Comment by dmicheletti** [comment]
Nothing about the source TCL changes, just updating image and README text.

**Comment by dmicheletti** [comment]
Can an admin merge this please so I may close my CR?

**Comment by lay-xilinx** [comment]
ok to test

**Comment by lay-xilinx** [comment]
ok to test

**Pull request merged**
