### PR TITLE
CR-1140160 - Changing "find and replace" in run.tcl from Linux utilities to native TCL for Windows support

### PR DESCRIPTION
**Pull request by dmicheletti**

### CODE REVIEW

**Comment by lay-xilinx** [comment]
ok to test

**Comment by lay-xilinx** [comment]
ok to test

**Comment by lay-xilinx** [comment]
retest this please

**Comment by Abhinav2016** [comment]
OK to retest

**Comment by lay-xilinx** [comment]
retest please

**Comment by lay-xilinx** [comment]
retest please

**Comment by lay-xilinx** [comment]
ok to test

**Comment by lay-xilinx** [comment]
retest this please

**Pull request closed without merging**
