### PR TITLE
CR-1142788 [2022.1] HSDP CED added

### PR DESCRIPTION
**Pull request by rishibharadwajs**
[2022.1] HSDP CED added

### CODE REVIEW

**Comment by vsrunga** [comment]
@rishibharadwajs  - As 2022.1 is a released branch, merge can happen only for the pull requests that are SRCB approved, else pipeline will fail.  Please go though "CR Requirements for Released Branches" section for more details https://gitenterprise.xilinx.com/XHUB/XilinxCEDStore/blob/master/README.md

**Comment by rishibharadwajs** [comment]
[CR-1142788](https://jira.xilinx.com/browse/CR-1142788)
CR has been created and approved.

**Comment by Abhinav2016** [comment]
OK to test

**Comment by lay-xilinx** [comment]
ok to test

**Comment by lay-xilinx** [comment]
retest this please

**Comment by lay-xilinx** [comment]
Looks like in the addOptions function, you try calling the part as a command.  This needs to be fixed in the PR.  See last line of code snippet below:

  # load part/pkg stuff here
  set toks [split ${PROJECT_PARAM.PART} "-"]
  set part [lindex $toks 0]
  log "part : $part $currentDir"
  # run factory proc to create proper get_all_quads and other device-specific procs
  $part

**Pull request merged**
