### PR TITLE
2020.2

### PR DESCRIPTION
**Pull request by mep-xilinx**
First Versal IBERT CED

### CODE REVIEW

**Comment by Premduth** [comment]
ok to test

**Comment by lay-xilinx** [comment]
ok to test

**Comment by lay-xilinx** [comment]
ok to test

**Comment by lay-xilinx** [comment]
closing, checked in with PR 86.  Needed to modify the files a bit to have a "default"  If no options, then CED defaults to using the first bank for a single Rx/Tx pair

**Pull request closed without merging**
