### PR TITLE
CR-1160396 - Versal CPM5 QDMA Simulation Design Update wrt Part

### PR DESCRIPTION
**Pull request by medamsindhu**
Updated current part with Production Part for  Versal CPM5 QDMA Simulation Design

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by sabarinaxil** [comment]
retest this please

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by lay-xilinx** [comment]
retest this please

**Comment by lay-xilinx** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by sabarinaxil** [comment]
retest this please

**Pull request merged**
