### PR TITLE
CR-1160152 - Add HSDP CED

### PR DESCRIPTION
**Pull request by havishxilinx**

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by lay-xilinx** [comment]
retest this please

**Comment by lay-xilinx** [comment]
Please no : in the CR number

**Comment by ADubeyAMD** [comment]
ok to test

**Comment by sabarinaxil** [comment]
retest this please

**Comment by sabarinaxil** [comment]
retest this please

**Comment by sabarinaxil** [comment]
retest this please

**Pull request merged**
