### PR TITLE
CR-1157570 fixed issues with 2023.1 chipscopy CED

### PR DESCRIPTION
**Pull request by mep-xilinx**

### CODE REVIEW

**Comment by ADubeyAMD** [comment]
ok to test

**Review by vsrunga — APPROVED** [review]

**Comment by vsrunga** [comment]
ok to test

**Comment by mep-xilinx** [comment]
[AMD Official Use Only - General]

Not sure where the error is coming from, it works in today's build.

**Comment by ADubeyAMD** [comment]
retest this please

**Comment by lay-xilinx** [comment]
ok to test

**Comment by ADubeyAMD** [comment]
Hi @mep-xilinx, the pipeline is giving the following errors: 23:27:18 [17-Apr-2023 23:27:18] {update_catalog.py:699} INFO - ERROR: Failed to execute basic flow on example designs
23:27:18 [17-Apr-2023 23:27:18] {update_catalog.py:699} INFO - ERROR: ERROR: [Common 17-69] Command failed: Run 'impl_1' is not active

From 2023.1 we have commented out the implementation runs is test.tcl as shown below:
image

But somehow the error is happening at impl_1 run. I am still investigating what is happening here.

**Comment by sabarinaxil** [comment]
retest this please

**Pull request closed without merging**
