### PR TITLE
Update mpsoc_preset.tcl

### PR DESCRIPTION
**Pull request by shivakemidi**
adding support for T1 boards

### CODE REVIEW

**Comment by vsrunga** [comment]
ok to test

**Review by vsrunga — APPROVED** [review]

**Comment by sabarinaxil** [comment]
retest this please

**Comment by vsrunga** [comment]
ok to test

**Comment by vsrunga** [comment]
Pipelining fails due to 
CR: https://jira.xilinx.com/browse/CR-1073334
AR: https://xilinx.sharepoint.com/sites/xkb/SitePages/ArticleViewer.aspx?articleNumber=75516

Hence merging the change manually

**Pull request merged**
